# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b6ddfd75a27626c1ca7e06cb35fc67c"
name = "TapitaTraning2"
application_url = "https://proceeding-pottery-potato-carrying.trycloudflare.com"
embedded = true
handle = "tapitatraning2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://proceeding-pottery-potato-carrying.trycloudflare.com/auth/callback", "https://proceeding-pottery-potato-carrying.trycloudflare.com/auth/shopify/callback", "https://proceeding-pottery-potato-carrying.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
